---
title: "lab6"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{lab6}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction
```{r setup}
library(lab6)
```

## Data for the lab 

```{r setup}
RNGversion(min(as.character(getRversion()),"3.5.3"))

##old sampler used for backward compatibility
## suppressWarnings() can be used so that the above warning is not displayed
set.seed(42, kind = "Mersenne-Twister", normal.kind = "Inversion")
n <- 2000
knapsack_objects <-
  data.frame(
    w=sample(1:4000, size = n, replace = TRUE),
    v=runif(n = n, 0, 10000)
  )
```

## Brute Force Knapsack
Question: How much time does it takes to run the algorithm for n = 16 objects?
```{r}
brute_force_knapsack(knapsack_objects[1:16, ], W = ????)
```

## Dynamic Knapsack
Question: How much time does it takes to run the algorithm for n = 500 objects?
```{r}
knapsack_dynamic(knapsack_objects[1:500, ], W = ????)
```



## Greedy Heuristic Knapsack
Question: How much time does it takes to run the algorithm for n = 1000000 objects?
```{r}
Change the function to the greedy and need to change the data to 1000000 object 
knapsack_dynamic(knapsack_objects[1:1000000, ], W = ????)
```

